name: dev_widgets
version: 1.0.1+1
publish_to: none
description: Cross-platform utilities for developers.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  brazil: ^1.0.0
  characters: ^1.3.0
  code_text_field: ^1.1.0
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_markdown: ^0.6.12
  flutter_riverpod: ^2.0.2
  flutter_widget_from_html: ^0.14.11
  go_router: ^13.0.1
  highlight: ^0.7.0
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.9
  html_unescape: ^2.0.0
  ipsum: ^1.0.1
  json2yaml: ^3.0.1
  json_dart_generator: ^1.1.0+1
  multi_split_view: ^2.1.0
  package_info_plus: ^5.0.1
  path: ^1.8.2
  path_provider: ^2.0.11
  pretty_diff_text: ^1.0.0
  recase: ^4.1.0
  responsive_framework: ^0.2.0
  screenshot: ^2.1.0
  url_launcher: ^6.1.6
  uuid: ^4.2.2
  xml: ^6.1.0
  yaml: ^3.1.1
  yaru: ^1.2.1
  yaru_colors: ^0.1.0
  yaru_widgets: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/icon/icon.png
    - assets/translations/

  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf

    - family: Hack
      fonts:
        - asset: fonts/Hack-Regular.ttf

    - family: Monocraft
      fonts:
        - asset: fonts/Monocraft.otf

    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMonoNL-Regular.ttf
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  web:
    generate: true
  windows:
    generate: true
  linux:
    generate: true
