name: devtoys
version: 1.0.0+1
publish_to: none
description: Cross-platform version of DevToys, a Swiss Army knife for developers.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  code_text_field:
    git:
      url: https://github.com/BertrandBev/code_field
      ref: 66d4e56f14bc0073cd967149a929c6b670ffc74c

  desktop_window: ^0.4.0
  dropdown_search: ^5.0.3
  file_picker: ^5.2.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.12
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  html_unescape: ^2.0.0
  image_downloader_web: ^1.0.2
  ipsum: ^1.0.1
  json2yaml: ^3.0.0
  json_to_dart: ^1.0.5
  path_provider: ^2.0.11
  pretty_diff_text: ^1.0.0
  resizable_widget: ^1.0.5
  responsive_framework: ^0.2.0
  screenshot: ^1.2.3
  uuid: ^3.0.6
  xml: ^6.1.0
  yaml: ^3.1.1
  yaru: ^0.3.3
  yaru_colors: ^0.1.0
  yaru_widgets: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
